[package]
name = "test_utils"
version = "0.1.0"
authors = ["Matthew Healy <matthew@liamhealy.xyz>"]
edition = "2018"

[dependencies]
quote = "1.0.9"

[dependencies.syn]
version = "1.0.64"
features = ["full"]

[lib]
proc_macro = true
