[package]
name = "ei_cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ei_lexer = { path = "../ei_lexer" }
ei_parser = { path = "../ei_parser" }